

CREATE TABLE IF NOT EXISTS `Lst_Cat` (
  `CatId` int(11) NOT NULL,
  `CategoryParentId` int(11) DEFAULT NULL,
  `Name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=19012 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `Lst_Goods` (
  `GoodId` int(11) NOT NULL,
  `Name` varchar(250) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=492863 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `Lst_GoodsToCat` (
  `GoodToCatId` int(10) unsigned NOT NULL,
  `GoodId` int(11) NOT NULL DEFAULT '0',
  `CatId` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=5960169 DEFAULT CHARSET=utf8;

ALTER TABLE `Lst_Cat`
  ADD PRIMARY KEY (`CatId`);

ALTER TABLE `Lst_Goods`
  ADD PRIMARY KEY (`GoodId`);

ALTER TABLE `Lst_GoodsToCat`
  ADD PRIMARY KEY (`GoodToCatId`),
  ADD UNIQUE KEY `UK_Lst_GoodsToCat` (`GoodId`,`CatId`);


ALTER TABLE `Lst_Cat`
  MODIFY `CatId` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=19012;
ALTER TABLE `Lst_Goods`
  MODIFY `GoodId` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=492863;
ALTER TABLE `Lst_GoodsToCat`
  MODIFY `GoodToCatId` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5960169;COMMIT;